export const products = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    price: 299.99,
    category: "Electronics",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    description: "High-quality wireless headphones with noise cancellation and premium sound quality. Features include 30-hour battery life, touch controls, and premium build quality.",
  },
  {
    id: 2,
    name: "Minimalist Watch",
    price: 199.99,
    category: "Fashion",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    description: "Elegant minimalist watch with genuine leather strap. Perfect for both casual and formal occasions.",
  },
  {
    id: 3,
    name: "Modern Desk Lamp",
    price: 89.99,
    category: "Home & Living",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c",
    description: "Adjustable LED desk lamp with multiple brightness levels and color temperatures. Energy-efficient and perfect for your workspace.",
  },
  {
    id: 4,
    name: "Premium Yoga Mat",
    price: 79.99,
    category: "Sports",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2",
    description: "Professional-grade yoga mat with excellent grip and cushioning. Eco-friendly materials and perfect thickness for all types of yoga.",
  },
  {
    id: 5,
    name: "Smart Fitness Tracker",
    price: 149.99,
    category: "Electronics",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6",
    description: "Advanced fitness tracker with heart rate monitoring, sleep tracking, and smartphone notifications. Water-resistant and long battery life.",
  },
  {
    id: 6,
    name: "Leather Backpack",
    price: 129.99,
    category: "Fashion",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
    description: "Handcrafted leather backpack with laptop compartment. Perfect for daily commute or weekend trips.",
  },
  {
    id: 7,
    name: "Ceramic Plant Pot",
    price: 34.99,
    category: "Home & Living",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411",
    description: "Modern ceramic plant pot with drainage hole and saucer. Perfect for indoor plants and home decoration.",
  },
  {
    id: 8,
    name: "Basketball",
    price: 29.99,
    category: "Sports",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1519861155730-0b5fbf0dd889",
    description: "Official size and weight basketball with superior grip. Suitable for indoor and outdoor play.",
  },
];

export const categories = [
  {
    name: "Electronics",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661",
    description: "Latest gadgets and electronic devices",
  },
  {
    name: "Fashion",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050",
    description: "Trendy clothing and accessories",
  },
  {
    name: "Home & Living",
    image: "https://images.unsplash.com/photo-1484101403633-562f891dc89a",
    description: "Modern home decor and essentials",
  },
  {
    name: "Sports",
    image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
    description: "Sports equipment and accessories",
  },
];